kind: pipeline
type: docker
name: linux-amd64
DRONE_TIMEOUT=5h
platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: brock5555/ktt
  environment:
    PASSWORD:
      from_secret: GH_TOKEN
  commands:
  - ls
  - apt update
  - apt install git -y
  - git clone https://dozzler555:$PASSWORD@github.com/dozzler555/ttk source
  - cd source
  - bash start.sh
